# Generated by Django 3.1.3 on 2021-11-05 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20211105_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 4, 8, 18, 826222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 4, 8, 18, 826181, tzinfo=utc)),
        ),
    ]
