# Generated by Django 3.1.3 on 2021-11-05 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20211105_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 14, 23, 28, 13689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 14, 23, 28, 13663, tzinfo=utc)),
        ),
    ]
