# Generated by Django 3.1.3 on 2022-01-02 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20211121_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 18, 44, 23, 105346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 18, 44, 23, 105320, tzinfo=utc)),
        ),
    ]
