# Generated by Django 3.1.3 on 2022-01-24 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20220102_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 9, 46, 5, 28697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 9, 46, 5, 28667, tzinfo=utc)),
        ),
    ]
