# Generated by Django 3.1.3 on 2021-11-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211105_0408'),
        ('team', '0002_auto_20211105_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='task',
            name='documentation',
            field=models.FileField(blank=True, upload_to='project_documents/%Y/%m/%d'),
        ),
    ]
