# Generated by Django 3.1.3 on 2022-01-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
