# Generated by Django 3.1.3 on 2021-11-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyinfo',
            old_name='subject',
            new_name='course',
        ),
    ]
